# Generated by Django 5.2.7 on 2025-10-31 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('isTeamBased', models.BooleanField(default=False)),
                ('primary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sports', to=settings.AUTH_USER_MODEL)),
                ('secondary', models.ManyToManyField(related_name='secondary_sports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Fourth Year (BE)')], default='FE', max_length=2)),
                ('branch', models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artifical Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default='COMPS', max_length=6)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('registration_modified', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artifical Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default='COMPS', max_length=6)),
                ('members', models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
        ),
    ]
