# Generated by Django 5.2.7 on 2025-11-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
