# Generated by Django 5.2.7 on 2025-11-28 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_alter_results_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('denied', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('student', 'sport'), name='unique_student_sport_registration'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='registeration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.registration'),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team'),
        ),
        migrations.AddConstraint(
            model_name='teamrequest',
            constraint=models.UniqueConstraint(fields=('registeration', 'team'), name='unique_registration_team_request'),
        ),
    ]
