# Generated by Django 5.2.7 on 2025-11-03 21:08

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_student_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', authentication.models.StudentManager()),
            ],
        ),
    ]
