# Generated by Django 5.2.7 on 2025-11-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_student_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('COMPS', 'Computer Engineering'), ('IT', 'Information Technology'), ('AIML', 'CSE Artifical Intelligence and Machine Learning'), ('DS', 'CSE Data Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], default='COMPS', max_length=6),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Fourth Year (BE)')], default='FE', max_length=2),
        ),
    ]
