# Generated by Django 5.2.7 on 2025-11-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_student_branch_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_manageing',
            field=models.BooleanField(default=False),
        ),
    ]
