# Generated by Django 5.2.7 on 2025-11-23 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_student_is_manageing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_manageing',
            new_name='is_managing',
        ),
    ]
